# Generated by Django 3.1.7 on 2021-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='clubName',
            field=models.CharField(default='CLUB', max_length=200),
        ),
    ]
