# Generated by Django 3.1.7 on 2021-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='combinated',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'HEPTATLÓN'), (2, 'DECATLÓN'), (3, 'DEFAULT')], default=0),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='round',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'SERIES'), (2, 'SERIES C/T'), (3, 'FINAL'), (4, 'FINAL C/T'), (5, 'SEMIFINAL')], default=0),
        ),
    ]
