# Generated by Django 3.1.7 on 2021-10-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20211026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpassignments',
            name='strAthle',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='jumpassignments',
            name='strClub',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='midassignments',
            name='strAthle',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='midassignments',
            name='strClub',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='speedassignments',
            name='strAthle',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='speedassignments',
            name='strClub',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='throwassignments',
            name='strAthle',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='throwassignments',
            name='strClub',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
