# Generated by Django 3.1.7 on 2021-10-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20211027_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpparticipation',
            name='assignmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.jumpassignments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jumpparticipation',
            name='pNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jumpparticipation',
            name='result',
            field=models.CharField(default='X', max_length=10),
        ),
        migrations.AddField(
            model_name='jumpparticipation',
            name='wind',
            field=models.CharField(default='..', max_length=10),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='gender',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'DAMAS'), (2, 'VARONES'), (3, ' ')], default=0),
        ),
    ]
