# Generated by Django 3.1.7 on 2021-10-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20211027_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrowParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNumber', models.IntegerField(default=0)),
                ('result', models.CharField(default='X', max_length=10)),
                ('assignmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigneds', to='competition.throwassignments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Throw',
        ),
    ]
