# Generated by Django 3.1.7 on 2021-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_inscriptions_strathle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='strClub',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
    ]
