# Generated by Django 3.1.7 on 2021-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_inscriptions_strclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='series',
            field=models.BooleanField(default=False),
        ),
    ]
