# Generated by Django 3.1.7 on 2021-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_competitions_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpassignments',
            name='strAthle',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jumpassignments',
            name='strClub',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='midassignments',
            name='strAthle',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='midassignments',
            name='strClub',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='speedassignments',
            name='strAthle',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='speedassignments',
            name='strClub',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='throwassignments',
            name='strAthle',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='throwassignments',
            name='strClub',
            field=models.CharField(default='PIVOTE', max_length=200),
        ),
    ]
