# Generated by Django 3.1.7 on 2021-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_auto_20211117_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='observation',
            field=models.CharField(blank=True, default='S/C', max_length=200, null=True),
        ),
    ]
