# Generated by Django 3.1.7 on 2021-11-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competitions_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='status',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'ACTIVO'), (2, 'REALIZADO'), (3, 'SUSPENDIDO'), (4, 'APLAZADO'), (5, 'DESACTIVADO')], default=1),
        ),
    ]
