# Generated by Django 3.1.7 on 2021-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_auto_20211130_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpassignments',
            name='place',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='midassignments',
            name='place',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='speedassignments',
            name='place',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='throwassignments',
            name='place',
            field=models.IntegerField(default=99),
        ),
    ]
