# Generated by Django 3.1.7 on 2021-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_auto_20211204_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='inscriptionType',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'TITULAR'), (2, 'RESERVA')], default=1),
        ),
    ]
