# Generated by Django 3.1.7 on 2021-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_inscriptions_inscriptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpassignments',
            name='competititonNumber',
            field=models.IntegerField(default=0),
        ),
    ]
