# Generated by Django 3.1.7 on 2021-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='athletes',
            name='birthdate',
            field=models.DateField(default='2021-07-25'),
        ),
        migrations.AddField(
            model_name='athletes',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'SIN CATEGORIA'), (1, 'U16'), (2, 'U18'), (3, 'U20'), (4, 'U23'), (5, 'TD'), (6, 'CD'), (7, 'A'), (8, 'M')], default=0),
        ),
        migrations.AddField(
            model_name='athletes',
            name='cellphone',
            field=models.CharField(blank=True, default='.', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='coach',
            field=models.CharField(blank=True, default='.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='email',
            field=models.CharField(blank=True, default='.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='height',
            field=models.CharField(blank=True, default='.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='region',
            field=models.CharField(blank=True, default='.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='size',
            field=models.CharField(blank=True, default='.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
