# Generated by Django 3.1.7 on 2021-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_auto_20211026_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='cellphone',
            field=models.CharField(default='.', max_length=9),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='coach',
            field=models.CharField(default='.', max_length=10),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='email',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='height',
            field=models.CharField(default='.', max_length=4),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='region',
            field=models.CharField(default='.', max_length=10),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='size',
            field=models.CharField(default='.', max_length=4),
        ),
    ]
