# Generated by Django 3.1.7 on 2021-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0004_auto_20211027_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'DAMAS'), (2, 'VARONES'), (3, ' ')], default=0),
        ),
    ]
