# Generated by Django 3.1.7 on 2021-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0007_athletes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'SIN CATEGORIA'), (1, 'U16'), (2, 'U18'), (3, 'U20'), (4, 'U23'), (5, 'TD'), (6, 'CD'), (7, 'A'), (8, 'M'), (9, 'Preparatoria')], default=0),
        ),
    ]
