# Generated by Django 3.1.7 on 2021-10-25 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championships',
            name='address',
            field=models.CharField(default='DIRECCION', max_length=50),
        ),
        migrations.AddField(
            model_name='championships',
            name='category',
            field=models.CharField(default='012345678', max_length=9),
        ),
        migrations.AddField(
            model_name='championships',
            name='championshipName',
            field=models.CharField(default='CAMPEONATO', max_length=200),
        ),
        migrations.AddField(
            model_name='championships',
            name='country',
            field=models.CharField(default='PAIS', max_length=50),
        ),
        migrations.AddField(
            model_name='championships',
            name='finishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='championships',
            name='limitAthletes',
            field=models.IntegerField(choices=[(0, 'Sin Limite'), (1, '1 Atleta por prueba'), (2, '2 Atletas por prueba'), (3, '3 Atletas por prueba'), (4, '4 Atletas por prueba'), (5, '5 Atletas por prueba')], default=0),
        ),
        migrations.AddField(
            model_name='championships',
            name='limitClubs',
            field=models.IntegerField(choices=[(0, 'Sin limite'), (1, '2 Pruebas Individuales'), (2, '2 Pruebas Individuales + Posta'), (3, '3 Pruebas Individuales'), (4, '3 Pruebas Individuales+ Posta')], default=0),
        ),
        migrations.AddField(
            model_name='championships',
            name='numberStages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championships',
            name='region',
            field=models.CharField(default='REGION', max_length=50),
        ),
        migrations.AddField(
            model_name='championships',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stages',
            name='adminId',
            field=models.CharField(default='ADMINISTRADOR', max_length=200),
        ),
        migrations.AddField(
            model_name='stages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stages',
            name='finishHour',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='stages',
            name='numCompetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stages',
            name='numStage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stages',
            name='stageName',
            field=models.CharField(default='ETAPA', max_length=200),
        ),
        migrations.AddField(
            model_name='stages',
            name='starHour',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
