# Generated by Django 3.1.7 on 2021-10-27 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_auto_20211027_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stages',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
