# Generated by Django 3.1.7 on 2021-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_auto_20211027_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='championships',
            name='status',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'ACTIVO'), (2, 'REALIZADO'), (3, 'SUSPENDIDO'), (4, 'APLAZADO'), (5, 'DESACTIVADO')], default=0),
        ),
    ]
