# Generated by Django 3.1.7 on 2021-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_auto_20211126_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='status',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'ACTIVO'), (2, 'REALIZADO'), (3, 'SUSPENDIDO'), (4, 'APLAZADO'), (5, 'DESACTIVADO')], default=1),
        ),
    ]
