# Generated by Django 3.1.7 on 2021-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0007_stages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
