# Generated by Django 3.1.7 on 2021-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0008_auto_20211126_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championships',
            name='category',
            field=models.CharField(default='0000010000', max_length=10),
        ),
    ]
