# Generated by Django 3.1.7 on 2021-12-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(default='', max_length=200)),
                ('evento', models.CharField(default='', max_length=200)),
                ('titulo', models.CharField(default='', max_length=200)),
                ('hora', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroserie', models.CharField(default='', max_length=200)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.competencia')),
            ],
        ),
    ]
