# Generated by Django 3.1.7 on 2021-11-17 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20211115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadmin',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fedachiadmin',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedachiadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='judge',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultsadmin',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultsadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackadmin',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
